version: "2"

linters:
  enable:
    - gosec
    - errcheck
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    paths:
      - "sdk"
    rules:
      - linters:
          - staticcheck
        text: "SA1019" # we do use deprecated APIs on purpose sometimes
